// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Subscribed is an autogenerated mock type for the Subscribed type
type Subscribed struct {
	mock.Mock
}

// SubscribedChannel provides a mock function with given fields: _a0
func (_m *Subscribed) SubscribedChannel(_a0 string) {
	_m.Called(_a0)
}

// SubscribedServices provides a mock function with given fields: _a0
func (_m *Subscribed) SubscribedServices(_a0 string) {
	_m.Called(_a0)
}
