// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// SanitizeInput provides a mock function with given fields:
func (_m *Services) SanitizeInput() {
	_m.Called()
}

// ServiceMenu provides a mock function with given fields:
func (_m *Services) ServiceMenu() {
	_m.Called()
}
